---
# Install aws ssm agent on Debian family system

- name: Debian | Check if snap is available
  stat:
    path: /usr/bin/snap
  register: snap_available

- name: Debian | Install with apt aws ssm agent
  apt:
    deb: "{{ ssm_package_url }}"
    state: present
  when: not snap_available.stat.exists

- name: Debian | Manage aws ssm agent service
  service:
    name: "{{ ssm_service }}"
    state: started
    enabled: yes
  when: not snap_available.stat.exists

- name: Debian | Install with snap aws ssm agent
  snap:
    name: amazon-ssm-agent
    classic: yes
  when: snap_available.stat.exists

- name: Debian | Manage snap aws ssm agent service
  service:
    name: "{{ ssm_service }}"
    state: started
    enabled: yes
  when: snap_available.stat.exists
